#!/usr/bin/env python3
"""
Auto-update PROJECT.md when code changes are detected.

Scans the repo's controllers, services, and feature files and regenerates a single
machine-managed section of PROJECT.md (between AUTO-UPDATE markers). The section is
*regenerated in place* every run, so PROJECT.md never accumulates duplicate blocks.

Usage:
  python update-project-mindmap.py [--auto-commit]

Environment:
  CHANGED_FILES: Comma/newline-separated list of changed files (from git). Used only
                 to decide whether an update is warranted; the snapshot itself is built
                 from a full scan so it always reflects current state.
"""

import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime, timezone

# Everything between these markers is owned by this script and rewritten each run.
AUTO_BEGIN = "<!-- AUTO-UPDATE:BEGIN (generated by update-project-mindmap.py — do not edit inside this block) -->"
AUTO_END = "<!-- AUTO-UPDATE:END -->"

# File kinds that make an update worthwhile.
RELEVANT_SUFFIXES = (".java", ".cs", ".csproj", ".feature")

# Directories that never contain source we care about.
SKIP_DIRS = {"bin", "obj", "bin-tests", "obj-tests", "target", ".git", ".venv",
             "node_modules", ".vs", "TestResults", "__pycache__"}


class ProjectMindmapUpdater:
    def __init__(self, repo_root: str = "."):
        self.repo_root = Path(repo_root).resolve()
        self.project_md = self.repo_root / "PROJECT.md"
        self.changed_files = self._get_changed_files()

    # ----- change detection (gate only) ---------------------------------------

    def _get_changed_files(self) -> List[str]:
        raw = os.environ.get("CHANGED_FILES", "")
        changed = [f.strip() for f in re.split(r"[,\n]", raw) if f.strip()]
        if not changed:
            try:
                result = subprocess.run(
                    ["git", "diff", "--name-only", "HEAD~1..HEAD"],
                    capture_output=True, text=True, cwd=self.repo_root, check=False,
                )
                changed = [f.strip() for f in result.stdout.splitlines() if f.strip()]
            except Exception:
                changed = []
        return changed

    def _has_relevant_change(self) -> bool:
        return any(f.endswith(RELEVANT_SUFFIXES) for f in self.changed_files)

    # ----- discovery ----------------------------------------------------------

    def _discover(self):
        controllers, services, features = [], [], []
        for p in self.repo_root.rglob("*"):
            if not p.is_file():
                continue
            if SKIP_DIRS & set(p.parts):
                continue
            name = p.name
            rel = str(p.relative_to(self.repo_root))
            if name.endswith(("Controller.java", "Controller.cs")):
                controllers.append(rel)
            elif name.endswith(("Service.java", "Service.cs")):
                services.append(rel)
            elif name.endswith(".feature"):
                features.append(rel)
        return sorted(controllers), sorted(services), sorted(features)

    # ----- parsing ------------------------------------------------------------

    @staticmethod
    def _join_path(base: str, route: str) -> str:
        base = ("/" + base.strip("/")) if base.strip("/") else ""
        route = route.strip()
        if not route:
            return base or "/"
        if not route.startswith("/"):
            route = "/" + route
        return (base + route) if base else route

    def _parse_controller(self, filepath: str) -> Optional[Dict]:
        path = self.repo_root / filepath
        if not path.exists():
            return None
        content = path.read_text(errors="ignore")
        is_java = filepath.endswith(".java")

        if is_java:
            base_m = re.search(r'@RequestMapping\(\s*(?:value\s*=\s*)?"([^"]*)"', content)
            ann = re.compile(r'@(Get|Post|Put|Delete|Patch)Mapping\b\s*(?:\(\s*(?:value\s*=\s*)?"([^"]*)")?')
        else:
            base_m = re.search(r'\[Route\(\s*"([^"]*)"', content)
            ann = re.compile(r'\[Http(Get|Post|Put|Delete|Patch)\b\s*(?:\(\s*"([^"]*)")?')

        base = base_m.group(1) if base_m else ""
        # Return type may be generic (ActionResult<T>) and there may be intervening
        # attributes/annotations before `public` — so scan forward to the method's
        # own `public ... Name(` and take the identifier just before `(`.
        name_re = re.compile(r'public\s+[^;{()=]+?\s+(\w+)\s*\(')

        endpoints = []
        for m in ann.finditer(content):
            verb = m.group(1).upper()
            route = m.group(2) or ""
            nm = name_re.search(content[m.end():m.end() + 600])
            handler = nm.group(1) if nm else "?"
            endpoints.append({"method": verb, "path": self._join_path(base, route),
                              "handler": handler})
        return {"class": Path(filepath).stem, "file": filepath,
                "language": "java" if is_java else "dotnet", "endpoints": endpoints}

    def _parse_service(self, filepath: str) -> Optional[Dict]:
        path = self.repo_root / filepath
        if not path.exists():
            return None
        content = path.read_text(errors="ignore")
        lang = "java" if filepath.endswith(".java") else "dotnet"
        getter_prefix = "get" if lang == "java" else "Get"
        cls = Path(filepath).stem

        methods, seen = [], set()
        for m in re.finditer(
            r'public\s+(?:static\s+|virtual\s+|override\s+|async\s+|sealed\s+)*'
            r'([^;{()=]+?)\s+(\w+)\s*\(',
            content,
        ):
            ret = re.sub(r'\s+', ' ', m.group(1).strip())
            name = m.group(2)
            if name == cls or name.startswith(getter_prefix) or name in seen:
                continue
            seen.add(name)
            methods.append({"name": name, "returns": ret})
        return {"class": cls, "file": filepath, "language": lang, "methods": methods}

    def _parse_feature(self, filepath: str) -> Optional[Dict]:
        path = self.repo_root / filepath
        if not path.exists():
            return None
        content = path.read_text(errors="ignore")
        feat_m = re.search(r'Feature:\s*(.+)', content)
        scenarios = [s.strip() for s in
                     re.findall(r'Scenario(?:\s+Outline)?:\s*(.+)', content)]
        return {"feature": feat_m.group(1).strip() if feat_m else Path(filepath).stem,
                "file": filepath, "scenarios": scenarios, "count": len(scenarios)}

    # ----- rendering ----------------------------------------------------------

    def _existing_criticality(self, content: str) -> dict:
        """Preserve QA's per-controller criticality across regenerations. Keyed by
        'language:Class' because Java and .NET can share a class name (ProductController)."""
        out = {}
        for m in re.finditer(
            r'`([A-Za-z0-9_]+)`\s*\((java|dotnet)\)\s*[—-]\s*criticality:\s*(HIGH|MEDIUM|LOW)',
            content, re.IGNORECASE,
        ):
            out[f"{m.group(2).lower()}:{m.group(1)}"] = m.group(3).upper()
        return out

    def _existing_skip(self, content: str) -> str:
        """Preserve QA's 'skip these criticalities' setting (tolerant of the ** bold
        markers and of the older 'Skip test generation for criticality:' label)."""
        m = re.search(r'Skip[^\n]*criticality[^\n:]*:\s*\**\s*([A-Za-z0-9, ]+)',
                      content, re.IGNORECASE)
        return m.group(1).strip() if m else "NONE"

    def _render_region(self, controllers, services, features, criticality, skip_setting) -> str:
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        out = [
            AUTO_BEGIN, "",
            "## 🤖 Auto-Generated Snapshot", "",
            f"*Last updated: {ts} — regenerated automatically by "
            f"`update-project-mindmap.py`. Controller criticality and the skip line below are "
            f"QA-owned and preserved across regenerations; everything else is overwritten.*",
            "",
            "### Criticality & skip",
            "",
            "*QA: set each controller's criticality (LOW / MEDIUM / HIGH) in the list below, and "
            "list the level(s) to skip here (comma-separated, or NONE). When a push touches only "
            "skipped-criticality controllers, BOTH test generation and the regression run are "
            "skipped for it.*",
            "",
            f"**Skip criticality (generation + regression):** {skip_setting or 'NONE'}",
            "",
            "### API Endpoints", "",
        ]

        for lang, label in (("java", "Java (Spring Boot)"), ("dotnet", ".NET (ASP.NET Core)")):
            group = [c for c in controllers if c["language"] == lang and c["endpoints"]]
            if not group:
                continue
            out.append(f"**{label}**")
            out.append("")
            for c in group:
                lvl = criticality.get(f"{c['language']}:{c['class']}", "MEDIUM")
                out.append(f"- `{c['class']}` ({c['language']}) — criticality: {lvl}")
                for ep in c["endpoints"]:
                    out.append(f"  - `{ep['method']} {ep['path']}` → {ep['handler']}()")
            out.append("")

        svc = [s for s in services if s["methods"]]
        if svc:
            out.append("### Service Methods")
            out.append("")
            for s in svc:
                out.append(f"- `{s['class']}` ({s['language']})")
                for meth in s["methods"]:
                    out.append(f"  - {meth['name']}() → {meth['returns']}")
            out.append("")

        if features:
            total = sum(f["count"] for f in features)
            out.append(f"### Feature Coverage ({total} scenarios across {len(features)} files)")
            out.append("")
            for f in features:
                out.append(f"- **{f['feature']}** — {f['count']} scenario(s) "
                           f"(`{Path(f['file']).name}`)")
                for sc in f["scenarios"]:
                    out.append(f"  - {sc}")
            out.append("")

        out.append(AUTO_END)
        return "\n".join(out)

    # ----- assembly -----------------------------------------------------------

    def _clean(self, content: str) -> str:
        """Strip the previous managed region, legacy [AUTO-UPDATE] blocks, and stray
        duplicate 'Last Updated' lines so we can re-insert a single clean region."""
        # previous managed region
        content = re.sub(re.escape(AUTO_BEGIN) + r".*?" + re.escape(AUTO_END),
                         "", content, flags=re.DOTALL)
        # legacy inline blocks: '**[AUTO-UPDATE] ...:**' plus following bullet lines
        content = re.sub(r'\n*\*\*\[AUTO-UPDATE\][^\n]*\*\*\n(?:[-*] [^\n]*\n)*',
                         "\n", content)
        # stray top-of-file 'Last Updated' lines (the region carries the timestamp)
        content = re.sub(r'(?m)^\*Last Updated:.*\*\n?', "", content)
        # collapse 3+ blank lines
        content = re.sub(r'\n{3,}', "\n\n", content)
        return content

    def _insert_region(self, content: str, region: str) -> str:
        # Place the region just before the first '## ' heading; else append.
        m = re.search(r'(?m)^## ', content)
        if m:
            return content[:m.start()] + region + "\n\n" + content[m.start():]
        return content.rstrip() + "\n\n" + region + "\n"

    def run(self) -> bool:
        """Regenerate PROJECT.md's managed region. Returns True if the file changed."""
        if not self._has_relevant_change():
            print("ℹ️  No relevant (.java/.cs/.csproj/.feature) changes — skipping.")
            return False
        if not self.project_md.exists():
            print(f"⚠️  PROJECT.md not found at {self.project_md}")
            return False

        controllers_paths, service_paths, feature_paths = self._discover()
        controllers = [c for c in (self._parse_controller(p) for p in controllers_paths) if c]
        services = [s for s in (self._parse_service(p) for p in service_paths) if s]
        features = [f for f in (self._parse_feature(p) for p in feature_paths) if f]

        ep_count = sum(len(c["endpoints"]) for c in controllers)
        print(f"🔍 Scanned: {len(controllers)} controllers ({ep_count} endpoints), "
              f"{len(services)} services, {len(features)} feature files.")

        original = self.project_md.read_text()
        criticality = self._existing_criticality(original)   # preserve QA edits
        skip_setting = self._existing_skip(original)
        region = self._render_region(controllers, services, features, criticality, skip_setting)
        rebuilt = self._insert_region(self._clean(original), region)

        if rebuilt == original:
            print("ℹ️  PROJECT.md already up to date.")
            return False

        self.project_md.write_text(rebuilt)
        print("✅ PROJECT.md snapshot regenerated.")
        return True


def main() -> int:
    auto_commit = "--auto-commit" in sys.argv
    updater = ProjectMindmapUpdater()
    changed = updater.run()

    if changed and auto_commit:
        print("📤 Auto-committing PROJECT.md...")
        try:
            subprocess.run(["git", "add", "PROJECT.md"],
                           cwd=updater.repo_root, check=True)
            subprocess.run(["git", "commit", "-m",
                            "[auto] regenerate PROJECT.md snapshot"],
                           cwd=updater.repo_root, check=True)
            print("✅ Committed.")
        except subprocess.CalledProcessError as e:
            print(f"❌ Commit failed: {e}")
            return 1

    # No change is a normal no-op, not a failure — exit 0 so CI stays green.
    return 0


if __name__ == "__main__":
    sys.exit(main())
